<?php

namespace Test;

use PHPUnit\Framework\TestCase;

class Api extends TestCase
{
    private $http;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
